{-# LANGUAGE OverloadedStrings #-}

module Main where

-- import           Hitomi
import           Marumaru
import           Sucuri
import           Test.Hspec
import           Text.Show.Unicode


main :: IO ()
main = hspec $ do
  describe "Sucuri" $ do
    it "decode cloudflare sucuri ddos protector" $ do
      decode "ZT0nZ09jJy5jaGFyQXQoMikrJ0E5Jy5zbGljZSgxLDIpKyAnJyArJycrIjZtIi5jaGFyQXQoMCkgKyAgJycgKyAKU3RyaW5nLmZyb21DaGFyQ29kZSgweDMxKSArICcwJyArICAiNnQiLmNoYXJBdCgwKSArICJhc3VjdXIiLmNoYXJBdCgwKSsnRDYnLnNsaWNlKDEsMikrICcnICsgCic0JyArICAiIiArImFvIi5jaGFyQXQoMCkgKyAiOXN1Ii5zbGljZSgwLDEpICsgICcnICsnJysiYyIuc2xpY2UoMCwxKSArICdkJyArICAiIiArU3RyaW5nLmZyb21DaGFyQ29kZSg1NykgKyAgJycgKycnKyJibCIuY2hhckF0KDApICsgImZrIi5jaGFyQXQoMCkgKyAiOSIgKyAiYyIuc2xpY2UoMCwxKSArICAnJyArJzknICsgICAnJyArIAonZicgKyAgICcnICsnOHZUOScuc3Vic3RyKDMsIDEpICsiMWQiLmNoYXJBdCgwKSArICc8Yicuc2xpY2UoMSwyKSsgJycgKycnKyJjIiArICAnJyArJycrJzUnICsgICAnJyArIAonNScgKyAgICcnICsiMnN1Ii5zbGljZSgwLDEpICsgImFtIi5jaGFyQXQoMCkgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDB4MzQpICsgImMiICsgU3RyaW5nLmZyb21DaGFyQ29kZSg1MikgKyAnNicgKyAgJyc7ZG9jdW1lbnQuY29va2llPSdzdXMnLmNoYXJBdCgyKSsndScrJ2MnKydzdXUnLmNoYXJBdCgyKSsncicrJ2knKycnKydzdWN1cmlfJy5jaGFyQXQoNikrJ2MnKydscycuY2hhckF0KDApKydvJysndScrJ2RzJy5jaGFyQXQoMCkrJ3AnKydzdWN1cnInLmNoYXJBdCg1KSArICdvc3VjJy5jaGFyQXQoMCkrICd4c3VjdScuY2hhckF0KDApICArJ3knKydfJysnc3VjdXUnLmNoYXJBdCg0KSsgJ3N1Jy5jaGFyQXQoMSkrJ2lzdWMnLmNoYXJBdCgwKSsgJ3N1Y3VkJy5jaGFyQXQoNCkrICdfJysnJysnZHMnLmNoYXJBdCgwKSsnZCcrJycrJzMnKycyJysnJysnZXN1YycuY2hhckF0KDApKyAnc3VjdTInLmNoYXJBdCg0KSsgJzUnKyc3c3UnLmNoYXJBdCgwKSArJ2UnKyI9IiArIGUgKyAnO3BhdGg9LzttYXgtYWdlPTg2NDAwJzsgbG9jYXRpb24ucmVsb2FkKCk7"
        `shouldBe` "sucuri_cloudproxy_uuid_dd32e257e=c96106a64a9cd9bf9c9f91bc552a4c46"
  -- Marumaru.allMangas >>= uprint . take 10
  -- Hitomi.allMangas >>= uprint . take 10
